node_js:
- "0.10"
- "0.11"
language: node_js
install: "npm install"
script:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly --recursive -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
